# Generated by Django 4.2.3 on 2023-08-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=30)),
                ("current_club", models.CharField(max_length=30)),
                ("position", models.CharField(max_length=10)),
                ("market_value", models.CharField(max_length=10)),
            ],
        ),
    ]
